language: php
php:
  - 7.1
mysql:
  database: activecollab_database_migrations_test
  username: root
  encoding: utf8mb4
install:
  - composer install --dev
  - phpunit --version
before_script:
  - mysql -e 'create database activecollab_database_migrations_test'
script: vendor/bin/phpunit